# Generated by Django 4.1.3 on 2022-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='modificado')),
                ('tipo', models.CharField(choices=[('Chapa', 'Chapa'), ('Tubo', 'Tubo')], max_length=50, verbose_name='Tipo')),
                ('potencia', models.PositiveSmallIntegerField()),
                ('espessura', models.PositiveSmallIntegerField()),
                ('material', models.CharField(choices=[('carbon_steel', 'carbon_steel'), ('stainless_steel', 'stainless_steel'), ('aluminum', 'aluminum'), ('brass', 'brass'), ('galvanized', 'galvanized'), ('copper', 'copper')], max_length=50, verbose_name='Material')),
                ('gas', models.CharField(choices=[('O2', 'O2'), ('N2', 'N2'), ('Air', 'Air')], max_length=50, verbose_name='Gas')),
                ('cut_speed', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('lift_height', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('cut_height', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('cut_pressure', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('peak_power', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('duty_cycle', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('pulse_frequency', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('laser_on_delay', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('pierce_stage', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50, verbose_name='Piercing Stage')),
                ('step_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_height', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_gas', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_pressure', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_peak_power', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_duty_cycle', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_frequency', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('focus', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_extra_blow', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('step_time2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_height2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_gas2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_pressure2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_peak_power2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_duty_cycle2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_frequency2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('focus2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_time2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_extra_blow2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('step_time3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_height3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_gas3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_pressure3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_peak_power3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_duty_cycle3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_frequency3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('focus3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_time3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piercing_extra_blow3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
