# Generated by Django 4.1.3 on 2022-11-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='focus2',
            new_name='piercing_focus',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='focus3',
            new_name='piercing_focus2',
        ),
        migrations.AddField(
            model_name='parameter',
            name='piercing_focus3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='focus',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
