# Generated by Django 4.1.3 on 2022-12-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_focus2_parameter_piercing_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='piercing_gas',
            field=models.CharField(blank=True, choices=[('O2', 'O2'), ('N2', 'N2'), ('Air', 'Air')], max_length=50, null=True, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='piercing_gas2',
            field=models.CharField(blank=True, choices=[('O2', 'O2'), ('N2', 'N2'), ('Air', 'Air')], max_length=50, null=True, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='piercing_gas3',
            field=models.CharField(blank=True, choices=[('O2', 'O2'), ('N2', 'N2'), ('Air', 'Air')], max_length=50, null=True, verbose_name='Gas'),
        ),
    ]
