# Generated by Django 4.1.3 on 2022-12-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_parameter_potencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='potencia',
            field=models.CharField(max_length=10),
        ),
    ]
